[package]
name = "ds_210_final_project"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.4"
linfa-clustering = "0.6.1"
linfa = "0.6.1"
statistical = "1.0.0"
ndarray = "0.15.6"